# TODO: Use $PACKAGE_MANAGER instead of always yarn.
runs:
  using: composite
  steps:
    - run: yarn exec -s -- node $GITHUB_ACTION_PATH/fetch_node_headers.js >> "$GITHUB_OUTPUT"
      id: compute-node-targets-hash
      shell: bash
    - name: Restore node headers
      if: ${{ env.CACHE == 'true' }}
      id: cache-node-headers
      uses: actions/cache/restore@v4
      with:
        path: ${{ env.NODE_HEADERS_DIRECTORY }}
        key: node-headers-cache-${{ runner.os }}-version${{ env.NODE_VERSIONS }}-${{ steps.compute-node-targets-hash.outputs.hash }}
    - name: Fetch node headers
      if: ${{ steps.cache-node-headers.outputs.cache-hit != 'true' }}
      run: |
        yarn exec -s -- node $GITHUB_ACTION_PATH/fetch_node_headers.js $NODE_HEADERS_DIRECTORY
      shell: bash
    - name: Save node headers
      if: ${{ env.CACHE == 'true' && steps.cache-node-headers.outputs.cache-hit != 'true' }}
      uses: actions/cache/save@v3
      with:
        path: ${{ env.NODE_HEADERS_DIRECTORY }}
        key: ${{ steps.cache-node-headers.outputs.cache-primary-key }}
