name: Install Docker
runs:
  using: composite
  steps:
    - run: |
        curl -fsSL https://get.docker.com -o get-docker.sh
        sudo sh ./get-docker.sh
      shell: bash
    - run: |
        sudo usermod -aG docker $USER
        sudo apt-get install acl
        sudo setfacl --modify user:$USER:rw /var/run/docker.sock
      shell: bash
