# TODO: Remove this action when GA support lands for ARM machines.
name: Install Docker
runs:
  using: composite
  steps:
    - run: |
        RELEASE=$(lsb_release --release)
        CODENAME=$(lsb_release --codename)
        ARCH=$(uname -m)
        echo "https://download.docker.com/linux/ubuntu/dists/${CODENAME}/pool/stable/${ARCH}/containerd.io_1.7.20-1_${ARCH}.deb"
        sudo curl --parallel \
          -O "https://download.docker.com/linux/ubuntu/dists/${CODENAME}/pool/stable/${ARCH}/containerd.io_1.7.20-1_${ARCH}.deb" \
          -O "https://download.docker.com/linux/ubuntu/dists/${CODENAME}/pool/stable/${ARCH}/docker-buildx-plugin_0.16.2-1~ubuntu.${RELEASE}~${CODENAME}_${ARCH}.deb" \
          -O "https://download.docker.com/linux/ubuntu/dists/${CODENAME}/pool/stable/${ARCH}/docker-ce-cli_27.1.2-1~ubuntu.${RELEASE}~${CODENAME}_${ARCH}.deb" \
          -O "https://download.docker.com/linux/ubuntu/dists/${CODENAME}/pool/stable/${ARCH}/docker-ce_27.1.2-1~ubuntu.${RELEASE}~${CODENAME}_${ARCH}.deb" \
          -O "https://download.docker.com/linux/ubuntu/dists/${CODENAME}/pool/stable/${ARCH}/docker-compose-plugin_2.29.1-1~ubuntu.${RELEASE}~${CODENAME}_${ARCH}.deb"
        sudo dpkg -i ./containerd.io_1.7.20-1_${ARCH}.deb \
          ./docker-ce_27.1.2-1~ubuntu.${RELEASE}~${CODENAME}_${ARCH}.deb \
          ./docker-ce-cli_27.1.2-1~ubuntu.${RELEASE}~${CODENAME}_${ARCH}.deb \
          ./docker-buildx-plugin_0.16.2-1~ubuntu.${RELEASE}~${CODENAME}_${ARCH}.deb \
          ./docker-compose-plugin_2.29.1-1~ubuntu.${RELEASE}~${CODENAME}_${ARCH}.deb
      shell: bash
    - run: |
        sudo usermod -aG docker $USER
        sudo apt-get install acl
        sudo setfacl --modify user:$USER:rw /var/run/docker.sock
        sudo service docker start
      shell: bash
