runs:
  using: composite
  steps:
    - uses: actions/download-artifact@v3
    - run: $PACKAGE_MANAGER install --ignore-scripts
      shell: bash
      working-directory: ${{ env.DIRECTORY_PATH }}
    - run: yarn exec node $GITHUB_ACTION_PATH
      if: ${{ env.DOCKER_BUILDER == '' }}
      shell: bash
    - run: |
        docker run \
          -v $GITHUB_ACTION_PATH:/usr/action \
          -v $PWD:/usr/workspace \
          -e NAPI="$NAPI" \
          -e POSTBUILD="$POSTBUILD" \
          -e PREBUILD="$PREBUILD" \
          -e TARGET_NAME="$TARGET_NAME" \
          -e NAPI_RS="$NAPI_RS" \
          -e DIRECTORY_PATH="$DIRECTORY_PATH" \
          -e NODE_VERSIONS="$NODE_VERSIONS" \
          -w /usr/action \
          $DOCKER_BUILDER \
          /bin/bash -c 'yarn && cd /usr/workspace && yarn exec node /usr/action'
      if: ${{ env.DOCKER_BUILDER != '' }}
      shell: bash
    - uses: actions/upload-artifact@v3
      with:
        name: prebuilds
        path: prebuilds/**/*
