runs:
  using: composite
  steps:
    - run: $PACKAGE_MANAGER --ignore-scripts
      shell: bash
    - run: yarn exec node $GITHUB_ACTION_PATH
      shell: bash
    - uses: actions/upload-artifact@v2
      with:
        name: prebuilds
        path: prebuilds/**/*
