runs:
  using: composite
  steps:
    # Make artifacts previously uploaded by the parent workflow available to binding.gyp
    - uses: actions/download-artifact@v4
    # - name: Install node-gyp
    #   run: |
    #     yarn global add node-gyp --ignore-engines
    #   shell: bash
    - run: |
        $PACKAGE_MANAGER install --ignore-scripts
      shell: bash
      working-directory: ${{ env.DIRECTORY_PATH }}
    - run: echo "NODE_HEADERS_DIRECTORY=${DIRECTORY_PATH}/tmp_node_headers" >> "$GITHUB_ENV"
      shell: bash
    - uses: DataDog/action-prebuildify/headers@rochdev/napi-no-headers
      if: ${{ env.GYP == 'true' && env.CACHE == 'true' }}
    - run: yarn exec node $GITHUB_ACTION_PATH
      if: ${{ env.DOCKER_BUILDER == '' }}
      shell: bash
    - run: |
        docker run \
          -v $GITHUB_ACTION_PATH:/usr/action \
          -v $PWD:/usr/workspace \
          -v $NODE_HEADERS_DIRECTORY:/usr/node_headers \
          -e NAPI="$NAPI" \
          -e POSTBUILD="$POSTBUILD" \
          -e PREBUILD="$PREBUILD" \
          -e TARGET_NAME="$TARGET_NAME" \
          -e NAPI_RS="$NAPI_RS" \
          -e NEON="$NEON" \
          -e RUST="$RUST" \
          -e DIRECTORY_PATH="$DIRECTORY_PATH" \
          -e NODE_VERSIONS="$NODE_VERSIONS" \
          -e NODE_HEADERS_DIRECTORY="/usr/node_headers" \
          -e LIBC="$LIBC" \
          -w /usr/action \
          $DOCKER_BUILDER \
          /bin/bash -c 'yarn && cd /usr/workspace && yarn exec node /usr/action'
      if: ${{ env.DOCKER_BUILDER != '' }}
      shell: bash
    - uses: actions/upload-artifact@v4
      with:
        name: prebuilds-${{ github.job }}
        if-no-files-found: ignore
        path: ${{ env.DIRECTORY_PATH }}/prebuilds/**/${{ github.job }}/*
