runs:
  using: composite
  steps:
    # Make artifacts previously uploaded by the parent workflow available to binding.gyp
    - uses: actions/download-artifact@v4
    - name: Install node-gyp
      run: |
        yarn global add node-gyp --ignore-engines
      shell: bash
    - run: |
        $PACKAGE_MANAGER install --ignore-scripts
      shell: bash
      working-directory: ${{ env.DIRECTORY_PATH }}
    - run: |
        yarn exec -s -- node $GITHUB_ACTION_PATH/fetch_node_headers.js >> "$GITHUB_OUTPUT"
        echo "NODE_HEADERS_DIRECTORY=${DIRECTORY_PATH}/tmp_node_headers" >> "$GITHUB_ENV"
      id: compute-node-targets-hash
      shell: bash
    - name: Restore node headers
      if: ${{ env.CACHE == 'true' }}
      id: cache-node-headers
      uses: actions/cache/restore@v4
      with:
        path: ${{ env.NODE_HEADERS_DIRECTORY }}
        key: node-headers-cache-${{ runner.os }}-version${{ env.NODE_VERSIONS }}-${{ steps.compute-node-targets-hash.outputs.hash }}
    - name: Fetch node headers
      if: ${{ steps.cache-node-headers.outputs.cache-hit != 'true' }}
      run: |
        yarn exec -s -- node $GITHUB_ACTION_PATH/fetch_node_headers.js $NODE_HEADERS_DIRECTORY
      shell: bash
    - name: Save node headers
      if: ${{ env.CACHE == 'true' && steps.cache-node-headers.outputs.cache-hit != 'true' }}
      uses: actions/cache/save@v3
      with:
        path: ${{ env.NODE_HEADERS_DIRECTORY }}
        key: ${{ steps.cache-node-headers.outputs.cache-primary-key }}
    - run: yarn exec node $GITHUB_ACTION_PATH
      if: ${{ env.DOCKER_BUILDER == '' }}
      shell: bash
    - run: |
        docker run \
          -v $GITHUB_ACTION_PATH:/usr/action \
          -v $PWD:/usr/workspace \
          -v $NODE_HEADERS_DIRECTORY:/usr/node_headers \
          -e NAPI="$NAPI" \
          -e POSTBUILD="$POSTBUILD" \
          -e PREBUILD="$PREBUILD" \
          -e TARGET_NAME="$TARGET_NAME" \
          -e NAPI_RS="$NAPI_RS" \
          -e NEON="$NEON" \
          -e RUST="$RUST" \
          -e DIRECTORY_PATH="$DIRECTORY_PATH" \
          -e NODE_VERSIONS="$NODE_VERSIONS" \
          -e NODE_HEADERS_DIRECTORY="/usr/node_headers" \
          -e LIBC="$LIBC" \
          -w /usr/action \
          $DOCKER_BUILDER \
          /bin/bash -c 'yarn && cd /usr/workspace && yarn exec node /usr/action'
      if: ${{ env.DOCKER_BUILDER != '' }}
      shell: bash
    - uses: actions/upload-artifact@v4
      with:
        name: prebuilds-${{ github.job }}
        path: ${{ env.DIRECTORY_PATH }}/**/prebuilds/**/*
