name: Test (Neon)

on:
  push:
  pull_request:
  schedule:
    - cron: '0 4 * * *'

jobs:
  build:
    uses: ./.github/workflows/build.yml
    with:
      min-node-version: 14 # Neon only supports Node >=14 when using latest Rust
      cache: true
      neon: true
      package-manager: yarn
      target-name: test
      directory-path: ./test/neon
