name: Test (Neon)

on:
  push:
    branches:
      - main
  pull_request:
  schedule:
    - cron: '0 4 * * *'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref || github.run_id }}
  cancel-in-progress: true

jobs:
  build:
    uses: ./.github/workflows/build.yml
    with:
      min-node-version: 14 # Neon only supports Node >=14 when using latest Rust
      cache: true
      neon: true
      skip: linux-ia32
      package-manager: yarn
      target-name: test
      directory-path: ./test/neon
