name: Test (Neon)

on:
  push:
    branches:
      - main
  pull_request:
  schedule:
    - cron: '0 4 * * *'

jobs:
  build:
    uses: ./.github/workflows/build.yml
    with:
      min-node-version: 12
      napi: true
      package-manager: npm
      directory-path: ./test/napi
